/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pizzaSQL;

import org.junit.Test;

public class AppTest {
	@Test
	public void testAppHasAGreeting() throws Exception {
		//Controller app = new Controller();

		//Connection conn = app.makeConnection(App.user, App.URL, App.passwd);

		//assertNotNull(conn);
	}

	@Test
	public void testCreateCustomers() throws Exception {
		//Controller app = new Controller();
/*
		Connection conn = app.makeConnection(App.user, App.URL, App.passwd);
		String name = "pp";
		String phone = "616";
		String adress = "jdfjkbv";
		String postalCode = "316";
		String password = "jyfui";
		String email = "wecre.com";
		app.createCustomer(conn, name, postalCode, adress, email, phone, password);

		assertNotNull(conn);
		*/
	}
}
