/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pizzaSQL;

import org.junit.Test;
import static org.junit.Assert.*;

import java.sql.Connection;

public class AppTest {
	@Test
	public void testAppHasAGreeting() throws Exception {
		App app = new App();

		Connection conn = app.makeConnection();

		assertNotNull(conn);
	}

	@Test
	public void testCreateCustomers() throws Exception {
		App app = new App();

		Connection conn = app.makeConnection();
		String name = "pp";
		String phone = "616";
		String adress = "jdfjkbv";
		String postalCode = "316";
		String password = "jyfui";
		String email="wecre.com";
		app.createCustomer(conn, name, postalCode, adress, email,phone ,password);
		
		assertNotNull(conn);
	}
}
