insert into ingredient(id, ingredient) values ('1','farina');
insert into ingredient(id, ingredient) values ('2','pomodoro');
insert into ingredient(id, ingredient) values ('3','oil extr vergine ');
insert into ingredient(id, ingredient) values ('4','Salame');
insert into ingredient(id, ingredient) values ('5','Mozzarella');
insert into pizza(id, name) values ('1','margerita');
insert into pizza(id, name) values ('2','calabrese');
insert into pizza(id, name) values ('3','napolitana');
insert into pizza_ingredient(pizza_id,ingredient_id) values ('1','1');
insert into pizza_ingredient(pizza_id,ingredient_id) values ('1','2');
insert into pizza_ingredient(pizza_id,ingredient_id) values ('1','5');
