/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pizzaSQL;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Scanner;

public class App {
	public static String list_pizzasSQL = "SELECT id, name FROM pizza ";
	public static String getIngredient = "SELECT ingredient,price  FROM ingredient   INNER JOIN pizza_ingredient  ON pizza_ingredient.ingredient_id = ingredient.id  WHERE pizza_ingredient.pizza_id = ?;";

	public void mainLoop() throws Exception {
		while (true) {
			System.out.println("1 - list all avelable pizza");
			System.out.println("2 - Make an order ");
			System.out.println("3 - List of current orders ");
			System.out.println("4 - List of ingredient of pizza ");
			System.out.println("0 - Exit ");

			Scanner s = new Scanner(System.in);
			String str = s.nextLine();
			if (str.equals("1")) {
				listPizza();
			} else if (str.equals("2")) {
				makeOrder();
			} else if (str.equals("3")) {
				listOfOrder();
			} else if (str.equals("4")) {
				listOfIngredient();
			} else if (str.equals("0")) {
				break;
			}
		}
	}

	private void listOfIngredient() throws Exception {
		System.out.println("inside listOfIngredient methd");
		System.out.println("what pizza's information do you want ?");
		Scanner s = new Scanner(System.in);
		String str = s.nextLine();
		System.out.println("inside pizza list methd");
		Connection conn = makeconnection();
		java.sql.Statement statement = conn.createStatement();

		ResultSet resultPizza = statement.executeQuery(list_pizzasSQL);
		while (resultPizza.next()) {

			String nameOfPizza = resultPizza.getString("name");
			String idOfPizza = resultPizza.getString("id");

			System.out.println(idOfPizza + " " + nameOfPizza);
		}
	}

	private void listOfOrder() {
		System.out.println("inside listOfOrder methd");

	}

	private void makeOrder() {
		System.out.println("inside makeorder methd");

	}

	private void listPizza() throws Exception {
		System.out.println("inside pizza list methd");
		Connection conn = makeconnection();
		java.sql.Statement statement = conn.createStatement();

		ResultSet resultPizza = statement.executeQuery(list_pizzasSQL);
		while (resultPizza.next()) {

			String nameOfPizza = resultPizza.getString("name");
			String idOfPizza = resultPizza.getString("id");

			System.out.println(idOfPizza + " " + nameOfPizza);
		}

	}

	public Connection makeconnection() throws ClassNotFoundException {
		Connection conn = null;
		try {
			Class.forName("com.mysql.cj.jdbc.Driver");
			String url = "jdbc:mysql://127.0.0.1/pizza";
			String user = "root";
			String password = "tyghbn";

			conn = DriverManager.getConnection(url, user, password);
		} catch (SQLException ex) {
			// handle any errors
			System.out.println("SQLException: " + ex.getMessage());
			System.out.println("SQLState: " + ex.getSQLState());
			System.out.println("VendorError: " + ex.getErrorCode());
		}
		return conn;
	}

	public static void main(String[] args) throws Exception {
		new App().mainLoop();
	}
}
