/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pizzaSQL;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Scanner;

import pizzaSQL.model.Customer;
import pizzaSQL.model.Ingredients;
import pizzaSQL.model.Item;
import pizzaSQL.model.ItemType;
import pizzaSQL.model.Order;
import pizzaSQL.model.Rider;

public class Controller {
	/*
	 * FOR LOGIN:
	 */
	public static final String dbName = "pizza";
	public static final String user = "root";
	public static final String passwd = "dio";
	public static final String URL = "jdbc:mysql://127.0.0.1/" + dbName;

	protected static String customerId = "";
	protected static String customerEmail = "";
	protected static String customerPhone = "";
	protected static String customerPostcode = "";
	protected static Connection conn;

	private Hibernate hibernate;

	public Controller() throws Exception {

		hibernate = new Hibernate(user, passwd, URL);
	}

	public void mainLoop(Boolean showId) throws Exception {

		Scanner s;

		loop: while (true) {
			System.out.println(" ");
			System.out.println("""
					1 - Make an order
					2 - List all available Pizzas
					3 - List all available Drinks
					4 - List all available Desserts
					5 - List of current orders
					6 - Manage Customers
					7 - Cancel Orders
					0 - Exit\s""");
			s = new Scanner(System.in);
			String str = s.nextLine();
			switch (str) {
			case "1":
				makeOrder(s);
				break;
			case "2":
				System.out.println("\nAvailable pizza: \n");
				getListPizza(false);
				break;
			case "3":
				System.out.println("\nAvailable drinks: \n");
				getListDrinks(false);
				break;
			case "4":
				System.out.println("\nAvailable dessert: \n");
				getListDesserts(false);
				break;
			case "5":
				listOfOrder();
				break;

			case "6":
				manageCustomer(s);
				break;
			case "7":
				cancelOrders(s);
				break;
			case "0":
				break loop;
			}
		}
		s.close();
	}

	private void cancelOrders(Scanner s) throws Exception {

		Collection<Order> collection = hibernate.findAllOrdersInFiveMinutes();
		System.out.println("Please type the id of the order you want to cancel:");
		System.out.println(" ");
		for (Order order : collection) {
			System.out.printf("Order id: %d Customer name: %s Address: %s\n", order.getId(), order.getCustomer().getName(), order.getCustomer().getAddress());
		}
		Integer valueOf = null;
		try {
			while (valueOf == null) {
				String str = s.nextLine();
				valueOf = Integer.valueOf(str);

			}
		} catch (Exception e) {

			e.printStackTrace();
		}
		hibernate.deleteOrders(valueOf);
	}

	private void getListDesserts(boolean showId) throws Exception {

		Collection<Item> items = hibernate.findAllDessert();

		for (Item item : items) {

			Integer id = item.getId();
			String name = item.getName();
			Double price = item.getPrice();

			if (showId)
				System.out.printf("%2d - %-25s  price : %4.2f € \n", id, name, price);
			else
				System.out.printf("%-25s  price : %4.2f € \n", name, price);

		}

	}

	private void getListDrinks(boolean showId) throws Exception {

		Collection<Item> items = hibernate.findAllDrinks();

		for (Item item : items) {

			Integer id = item.getId();
			String name = item.getName();
			Double price = item.getPrice();

			if (showId)
				System.out.printf("%2d - %-25s  price : %4.2f € \n", id, name, price);
			else
				System.out.printf("%-25s  price : %4.2f € \n", name, price);

		}

	}
	/*
	 * FOR PIZZA
	 */

	private void getListPizza(Boolean showId) throws Exception {

		Collection<Item> items = hibernate.findAllPizza();

		for (Item item : items) {

			Integer id = item.getId();
			String name = item.getName();
			Double price = item.getPrice();
			Boolean isVeggie = item.isVeggie();
			Collection<Ingredients> ingredients = item.getIngredients();

			String listIng = new String();
			for (Ingredients o : ingredients) {
				listIng += o.getName() + ",";
			}
			StringBuffer sb = new StringBuffer(listIng);
			// invoking the method
			sb.deleteCharAt(sb.length() - 1);
			listIng = new String(sb);

			if (showId)
				System.out.printf("%2d - %-25s  price : %4.2f € veggie : %-3s (%s) \n", id, name, price, isVeggie, listIng);
			else
				System.out.printf("%-25s  price : %4.2f € veggie : %-3s (%s) \n", name, price, isVeggie, listIng);

		}

	}

	private void manageCustomer(Scanner s) throws Exception {

		loop: while (true) {
			System.out.println("\ninside manageCustomer method");
			System.out.println("1 - Create Customer ");
			System.out.println("2 - List All customers ");
			System.out.println("0 - Exit ");

			String str = s.nextLine();
			switch (str) {
			case "1":
				newCustomer(s);
				break;
			case "2":
				listAllCustomer();
				break;
			case "0":
				break loop;
			}

		}

	}

	private void listAllCustomer() throws Exception {
		System.out.println("Here we have a list of the current customers:");
		System.out.println(" ");

		Collection<Customer> list = hibernate.findAllCustomers();

		for (Customer customer : list) {

			Integer id = customer.getId();
			String name = customer.getName();
			String email = customer.getEmail();
			String phone = customer.getPhone();
			;

			System.out.println("Your customer id: " + id + ", Name: " + name + ", Email: " + email + ", Phone num: " + phone);

		}

	}

	private Customer newCustomer(Scanner s) throws SQLException {
		
		System.out.println("Insert your name: ");

		String name = s.nextLine();
		System.out.println("Insert your postal code: ");
		Integer postalCode = Integer.valueOf(s.nextLine());
		System.out.println("Insert your address: ");
		String address = s.nextLine();
		System.out.println("Insert your email: ");
		String email = s.nextLine();
		System.out.println("Insert your phone number: ");
		String phone = s.nextLine();
		System.out.println("Insert your password: ");
		String password = s.nextLine();

		Customer co = hibernate.createCustomer(name, postalCode, address, email, phone, password);
		return co;

	}


	private void makeOrder(Scanner s) throws Exception {

		System.out.println("Welcome, please enter your choices:");
		System.out.println(" ");
		getListPizza(true);
		getListDrinks(true);
		getListDesserts(true);
		Collection<Item> basket = new ArrayList<Item>();
		System.out.println(" ");
		System.out.println("Type the id of the products you wish to purchase. When you are done, type 'd' ");
		Boolean pizzaInBasket = false;
		while (true) {
			String string = s.nextLine();

			if (string.equals("d")) {
				if (pizzaInBasket) {
					break;
				} else

					System.out.println("You must orther at least one pizza ");
			} else {
				try {
					Item item = hibernate.findItemById(Integer.valueOf(string));
					if (item != null) {
						if (item.getItemType() == ItemType.pizza)
							pizzaInBasket = true;
						basket.add(item);
					}

				} catch (Exception e) {

				}
				System.out.println(basket);

			}
		}

//		Now we must handle the customer
		Customer newCustomer = null;
		loop: while (true) {
			System.out.println("\nPlease choose your customer:");
			System.out.println(" ");
			System.out.println("0 - Create Customer ");
			System.out.println("1 - List All customers ");

			String str = s.nextLine();
			switch (str) {
			case "0":
				newCustomer = newCustomer(s);
				break loop;
			case "1":
				listAllCustomer();
				System.out.println("Please enter customer ID");
				Integer id = Integer.valueOf(s.nextLine());
				newCustomer = hibernate.findCustomerById(id);
				if (newCustomer == null) {
					System.err.println("Sorry, we could not find your id "+id+" in our database");
				} else
					break loop;
			}

		}

		System.out.println("Please enter your discount code (if you dont have one, hit return)");

		String discountCode = s.nextLine();
		if (!discountCode.equals("")) {
			Boolean duplicated = hibernate.findDiscountDuplicate(discountCode);
			if (duplicated) {
				System.err.println("Discout code already used");
				discountCode = null;
			}

		}

		String newdiscount = generateDiscout(basket);
		if (!newdiscount.equals("-1"))
			System.out.printf("Your discount Code is  %s ", newdiscount);

		Order order = completCheckOut(basket, newCustomer, discountCode);

		printConfirmation(order);
	}

	public void printConfirmation(Order order) {
		System.out.printf("Order id:\t %d \n", order.getId());
		System.out.printf("Client Name:\t %s\n", order.getCustomer().getName());
		System.out.printf("Address:\t %s \n", order.getCustomer().getAddress());
		System.out.printf("Ready at:\t %s \n", order.getReadtAt());
		System.out.println("Your order's items below:");
		Collection<Item> details = order.getDetails();
		for (Item item : details) {
			System.out.printf("\t%s \n", item.getName());

		}
		System.out.printf("Price:\t %6.2f € \n", order.getPrice());

	}

	private String generateDiscout(Collection<Item> basket) {

		int count = 0;

		for (Item item : basket) {
			if (item.getItemType() == ItemType.pizza)
				count++;
		}
		if (count > 10)

			return RandomString.getAlphaNumericString(4);

		return new String("-1");
	}

	private Order completCheckOut(Collection<Item> basket, Customer newCustomer, String discount) throws Exception {

		return hibernate.completCheckOut(basket, newCustomer, discount);

	}

	
	public void listOfOrder() throws Exception {
		
		hibernate.resetRiderCameBack();
		
		System.out.println("List of order ready to leave:");
		System.out.println(" ");
		Collection<Order> ordersList = hibernate.findAllPendingOrder();
		for (Order order : ordersList) {
			System.out.printf("Id: %d Customer name: %s  Address: %s Postal code: %s \n", order.getId(), order.getCustomer().getName(), order.getCustomer().getAddress(),order.getCustomer().getPostalCode());
		}
		
		Collection <Rider> freeRider=hibernate.findFreeRiders();
		System.out.println(" ");
		System.out.println("Found the following free riders: ");
		System.out.println(" ");
		for (Rider rider : freeRider) {
			System.out.println(rider);
		}
		System.out.println(" ");
		System.out.println("Now we check for each free rider if there's an order to delivers");
		
		for (Order o : ordersList) {
			freeRider=hibernate.findFreeRiders();
			for (Rider rider : freeRider) {
				if(rider.getPostalCode().equals(o.getCustomer().getPostalCode()))
				{
					//the rider will came back in 30 min 
					Timestamp cameBack=new Timestamp(System.currentTimeMillis()+1800000);
					System.out.printf("Rider %s is free so will deliver order %d \n", rider.getName(),o.getId());
					rider.setAvailable(false);
					rider.setCameBack(cameBack);
					hibernate.updateRidersStatus(rider);
					hibernate.assignRiderToOrder(o,rider);
				}
			}
		}
		
	}

	public static void main(String[] args) throws Exception {
		new Controller().mainLoop(false);
	}
	
}
